spring:
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          database-platform: org.hibernate.dialect.MySQL8Dialect


